[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "NODE_ENV=production node dist/main"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
nodejs_version = "20"