[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node railway-entry.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs_version = "20"